### ISSUE TITLE
IDE 정상동작 테스트

### ISSUE THREAD

**Issue by ChoSeyoung** [visualkhh/simple-boot#1]
@visualkhh  > IntelliJ IDE 테스트 완료 👍 

ChoSeyoung > Eclipse 테스트

**Comment by visualkhh** [comment]
와우^^ 다행입니다. ​잘작동하는군요.
나중에 maven repository에 라이브러리가 정식으로 올라간다면 더욱더 간편하게 셋팅이 가능합니다.
좀더 다듬어 릴리지를 준비해야겠습니다. 많은 관심에 감사합니다.

**Comment by ChoSeyoung** [comment]
아직 테스트를 완벽하게 하진 않았으나 조금 문제가 있는듯 합니다.
이클립스에서 gradle project를 정확하게 인지하지 못하는 에러가 있는거같은데 
이부분에 있어서는 실험을 좀 더 해보고 comment 남기도록 하겠습니다.

**Comment by visualkhh** [comment]
example jar 패키징후  실행시  디펜던시 걸려있는 lib가 포함되지 않아 실행시 오류가 발생되는  경우가 있습니다.
이에 따른
gradle  plugin  "com.github.johnrengelman.shadow" 사용하여 디펜던시 걸려있는 lib를 jar안에 같이 패키징되도록 하였습니다.

![스크린샷 2021-04-20 오전 10 12 35](https://user-images.githubusercontent.com/11387354/115325073-f53d5a00-a1c5-11eb-95f1-898c01c70eb4.png)

실행
gradle :example:jar

cd simple-boot/example/build/libs
jara -jar all-in-one-example-1.0-SNAPSHOT-all.jar

감사합니다.
