### ISSUE TITLE
example jar build 후 실행시 hibernate 에러 발생

### ISSUE THREAD

**Issue by ChoSeyoung** [visualkhh/simple-boot#8]
![image](https://user-images.githubusercontent.com/42459067/115678614-aaba0a00-a38c-11eb-9a11-18619ba5422b.png)

**Comment by visualkhh** [comment]
프로세스가 비정상 종료되어
h2 server가 살아남아있어 
다음 구동시킬때 네트워크 충돌된듯하게 보입니다. 
간혈적 상황인듯합니다.
